export const SIDEBAR_STATE = "SIDEBAR_STATE";
export const SIDEBAR_MENU = "SIDEBAR_MENU";
export const MODAL_FILTER_STATE = "MODAL_FILTER_STATE";
export const STORES_LIST = "STORES_LIST";
export const PRODUCTS_LIST = "PRODUCT_LIST";
export const PAGINATION = "PAGINATION";